---
deployment:
  tasks:
    - export DEPLOYPATH=/home/fieldhoc/public/
    - /bin/cp -R GalleryPics $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp donate.html $DEPLOYPATH
    - /bin/cp gallery.html $DEPLOYPATH
    - /bin/cp pastYears.html $DEPLOYPATH
    - /bin/cp roster.html $DEPLOYPATH
    - /bin/cp schedule.html $DEPLOYPATH
    - /bin/cp 2016-2017.html $DEPLOYPATH
    - /bin/cp 2017-2018.html $DEPLOYPATH
    - /bin/cp 2018-2019.html $DEPLOYPATH
    - /bin/cp 2019-2020.html $DEPLOYPATH
    - /bin/cp 2020-2021.html $DEPLOYPATH
    - /bin/cp 2021-2022.html $DEPLOYPATH
    - /bin/cp 2022-2023.html $DEPLOYPATH
    - /bin/cp 2023-2024.html $DEPLOYPATH
